- name: Insert local yum repo configuration
  template:
    src: local.repo
    dest: /etc/yum.repos.d/local.repo

- name: Update Hosts File for others
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_default_ipv4'].address }}    {{item}} {{item}}.w251.mids"

state: present
  with_items:
    - "{{ groups['MandatoryHosts'] }}"

- name: Creates pip directory
  file: path=/root/.pip/ state=directory group=root owner=root

#- name: Insert local pip repo configuration
  #template:
    #src: /home/ansible/Files/pip.conf
    #dest: /root/.pip/pip.conf

- name: Insert local pip repo configuration
  copy:
    dest: /root/.pip/pip.conf
    content: |
      [global]
      index-url = http://piphost/pip/simple
      trusted-host = piphost

- name: Disallow password authentication
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Enable vi mode for root
  lineinfile:
    dest: /root/.bashrc
    regexp: '^set -o vi'
    line: 'set -o vi'
    state: present

- name: Add required packages
  yum: pkg={{item}} state=installed
  with_items: 
    - net-tools
    - java-1.8.0-openjdk.x86_64
    - python36u
    - python36u-pip.noarch
    - lsof

- name: Insert local java configuration
  copy:
    dest: /etc/profile.d/java.sh
    content: |
      export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
      export JRE_HOME=/usr/lib/jvm/jre

- name: Prevent softlayer from overwriting /etc/hosts
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '^manage_etc_hosts'
    line: 'manage_etc_hosts: False'
    state: present
