---
# Loads all servers into the playbook so their hosts file can be updated later
- hosts: all
  tasks: []

- name: Install cassandra nodes
  hosts: CassandraSlaves
  become: no

  roles:
    - updatehosts
    - common
    - cassandra
