---
- name: Install net utils
  hosts: test1
  become: no

  tasks:
  - name: Creates pip directory
    file: path=/root/.pip/ state=directory group=root owner=root

  - name: Creates cassandra directory
    file: path=/var/lib/cassandra state=directory group=root owner=root

  - name: Insert local yum repo configuration
    template:
      src: /home/ansible/Files/local.repo
      dest: /etc/yum.repos.d/local.repo

  - name: Insert local java configuration
    template:
      src: /home/ansible/Files/java.sh
      dest: /etc/profile.d/java.sh

  - name: Insert local pip repo configuration
    template:
      src: /home/ansible/Files/pip.conf
      dest: /root/.pip/pip.conf

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
      regexp="^PasswordAuthentication"
      line="PasswordAuthentication no"
      state=present
    notify: Restart ssh

  - name: Add required packages
    yum: pkg={{item}} state=installed
    with_items: 
      - net-tools
      - java-1.8.0-openjdk.x86_64
      - python36u
      - python36u-pip.noarch

  - parted:
      device: /dev/xvdc
      number: 1
      state: present

  - name: Create a ext4 filesystem on /dev/xvdc1 and check disk blocks
    filesystem:
      fstype: ext4
      dev: /dev/xvdc1
  
  - name: Mount up device by label
    mount:
      path: /var/lib/cassandra
      src: /dev/xvdc1
      fstype: ext4
      state: mounted

  - name: Add java
    yum:
      name: http://10.73.183.212/Cassandra/jre-8u181-linux-x64.rpm
      state: present

  - name: Add Cassandra
    yum:
      name: http://10.73.183.212/Cassandra/cassandra-3.11.2-1.noarch.rpm
      state: present

  - name: Add jemalloc
    yum:
      name: http://10.73.183.212/Cassandra/jemalloc-3.6.0-1.el7.x86_64.rpm
      state: present

  - name: Install numpy
    pip:
      name: pip,numpy,pandas
      executable: pip3.6

  - name: Set swappiness
    sysctl:
      name: vm.swappiness
      value: 10
      state: present

  - name: Set vm.max_map_count = 1048575
    sysctl:
      name: vm.max_map_count
      value: 1048575
      state: present

  - name: update cassandra config file
    template:
      src: /home/ansible/Files/cassandra.yaml
      dest: /etc/cassandra/conf/cassandra.yaml

  - name: Add hosts entries for primary cassandra servers
    lineinfile:
      path: /etc/hosts
      line: '10.73.183.227   cassandra1'

  - name: Add hosts entries for primary cassandra servers
    lineinfile:
      path: /etc/hosts
      state: present
      line: '10.73.183.233   cassandra2'

  - name: Add hosts entries for primary cassandra servers
    lineinfile:
      path: /etc/hosts
      state: present
      line: '10.73.183.207   cassandra3'

  - name: Enable cassandra service
    service: 
      name: cassandra
      enabled: yes

  - name: Start cassandra service
    service: 
      name: cassandra
      state: started

  #- name: "Build hosts file"
    #lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    #when: hostvars[item].ansible_default_ipv4.address is defined
    #with_items: groups['all']

  handlers:
  - name: Restart ssh
    service: name=ssh state=restarted
