---
# Loads all servers into the playbook so their hosts file can be updated later
- hosts: all
  tasks: []

- name: Install Kafka nodes
  hosts: KafkaBrokers
  become: no

  roles:
    - updatehosts
    - common
    - kafka
