---
# Loads all servers into the playbook so their hosts file can be updated later
- hosts: all
  tasks: []

- name: Install spark nodes
  hosts: SparkSlaves
  become: no

  roles:
    - updatehosts
    - common
    - sparkbase
    - sparkslave
