---
# Loads all servers into the playbook so their hosts file can be updated later
- hosts: all
  tasks: []

- name: Install zookeeper nodes
  hosts: ZookeeperKafka
  become: no

  roles:
    - common
    - updatehosts
    - zookeeper
